name: turkuyolu
description: Türkü Yolu turku yolu Çatı Katı Bilişim cati kati bilisim

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_sound: 9.2.13
  just_audio: 0.9.42

  http: ^1.2.2

  pull_to_refresh: ^2.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

devtools: false
